import {
  Injectable,
  NotFoundException,
  ForbiddenException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { buildSimplePdf } from './pdf-simple';
import { putReportObject } from './storage';

export type Branding = {
  brandName: string;
  brandPrimaryColor: string;
  brandLogoUrl: string | null;
  brandFooter: string;
};

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  private resolveBrand(org: {
    name: string;
    plan: string;
    brandName: string | null;
    brandPrimaryColor: string | null;
    brandLogoUrl: string | null;
    brandFooter: string | null;
  }): Branding {
    const whiteLabel = org.plan === 'AGENCY' || org.plan === 'PRO';
    if (!whiteLabel) {
      return {
        brandName: 'Answerspot',
        brandPrimaryColor: '#4f46e5',
        brandLogoUrl: null,
        brandFooter: 'Generated by Answerspot',
      };
    }
    return {
      brandName: org.brandName?.trim() || org.name || 'Answerspot',
      brandPrimaryColor: org.brandPrimaryColor || '#4f46e5',
      brandLogoUrl: org.brandLogoUrl || null,
      brandFooter:
        org.brandFooter?.trim() ||
        `Prepared by ${org.brandName || org.name} · Powered by Answerspot`,
    };
  }

  async generate(
    businessId: string,
    format: string | undefined,
    organizationId?: string,
  ) {
    const business = await this.prisma.business.findFirst({
      where: {
        id: businessId,
        deletedAt: null,
        ...(organizationId ? { organizationId } : {}),
      },
      include: {
        organization: {
          select: {
            id: true,
            name: true,
            plan: true,
            brandName: true,
            brandPrimaryColor: true,
            brandLogoUrl: true,
            brandFooter: true,
          },
        },
        visibilityScores: { orderBy: { computedAt: 'desc' }, take: 5 },
        recommendations: {
          where: { status: 'OPEN' },
          orderBy: { createdAt: 'desc' },
          take: 12,
        },
      },
    });
    if (!business) throw new NotFoundException('Business not found');

    if (organizationId && business.organizationId !== organizationId) {
      throw new ForbiddenException('Not your business');
    }

    const brand = this.resolveBrand(business.organization);
    const latest = business.visibilityScores[0];
    const fmt = (format || 'pdf').toLowerCase() === 'html' ? 'html' : 'pdf';
    const title = `${brand.brandName} Visibility Report — ${business.name}`;
    const generatedAt = new Date().toISOString();

    const lines = [
      `Business: ${business.name}`,
      `Location: ${business.city}, ${business.state}`,
      `Category: ${business.category}`,
      `Client workspace: ${business.organization.name} (${business.organization.plan})`,
      `Generated: ${generatedAt}`,
      ``,
      `Visibility Score: ${latest?.score ?? 'n/a'}`,
      latest?.breakdown
        ? `Breakdown: ${JSON.stringify(latest.breakdown)}`
        : 'Breakdown: n/a',
      ``,
      `Open recommendations (${business.recommendations.length}):`,
      ...business.recommendations.map(
        (r, i) =>
          `${i + 1}. [${r.severity}] ${r.title} — ${r.message.slice(0, 80)}`,
      ),
      ``,
      `Score history:`,
      ...business.visibilityScores.map(
        (s) =>
          `  ${s.computedAt.toISOString().slice(0, 16)} → ${s.score}`,
      ),
      ``,
      brand.brandFooter,
    ];

    let body: Buffer;
    let contentType: string;
    if (fmt === 'html') {
      const logo = brand.brandLogoUrl
        ? `<img src="${escapeHtml(brand.brandLogoUrl)}" alt="" style="max-height:48px;margin-bottom:12px"/>`
        : '';
      const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(
        title,
      )}</title>
<style>
:root{--brand:${escapeHtml(brand.brandPrimaryColor)}}
body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;color:#0f172a}
.header{border-bottom:3px solid var(--brand);padding-bottom:1rem;margin-bottom:1.5rem}
h1{font-size:1.4rem;color:var(--brand);margin:0.25rem 0}
.badge{display:inline-block;background:var(--brand);color:#fff;padding:0.2rem 0.6rem;border-radius:999px;font-size:0.75rem;font-weight:600}
pre{white-space:pre-wrap;background:#f8fafc;padding:1rem;border-radius:8px;border:1px solid #e2e8f0}
.footer{margin-top:2rem;font-size:0.8rem;color:#64748b;border-top:1px solid #e2e8f0;padding-top:1rem}
</style>
</head><body>
<div class="header">${logo}
<div class="badge">${escapeHtml(brand.brandName)}</div>
<h1>${escapeHtml(title)}</h1>
</div>
<pre>${escapeHtml(lines.join('\n'))}</pre>
<div class="footer">${escapeHtml(brand.brandFooter)}</div>
</body></html>`;
      body = Buffer.from(html, 'utf8');
      contentType = 'text/html; charset=utf-8';
    } else {
      body = buildSimplePdf({
        title,
        lines,
        brandLine: brand.brandName,
      });
      contentType = 'application/pdf';
    }

    const storageKey = `reports/${businessId}/${Date.now()}.${fmt}`;
    const stored = await putReportObject(storageKey, body, contentType);

    const row = await this.prisma.report.create({
      data: {
        businessId,
        format: fmt,
        title,
        storageKey: stored.storageKey,
        url: stored.url,
        sizeBytes: body.length,
      },
    });

    return {
      id: row.id,
      businessId,
      format: fmt,
      title,
      url: stored.url,
      storageKey: stored.storageKey,
      sizeBytes: body.length,
      mode: stored.mode,
      score: latest?.score ?? null,
      branding: brand,
      createdAt: row.createdAt,
    };
  }

  async list(businessId: string, organizationId: string) {
    const biz = await this.prisma.business.findFirst({
      where: { id: businessId, organizationId, deletedAt: null },
    });
    if (!biz) throw new NotFoundException('Business not found');
    return this.prisma.report.findMany({
      where: { businessId },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
  }
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
