import {
  Injectable,
  NotFoundException,
  ForbiddenException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { buildSimplePdf } from './pdf-simple';
import { putReportObject } from './storage';

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  async generate(
    businessId: string,
    format: string | undefined,
    organizationId?: string,
  ) {
    const business = await this.prisma.business.findFirst({
      where: {
        id: businessId,
        deletedAt: null,
        ...(organizationId ? { organizationId } : {}),
      },
      include: {
        organization: { select: { id: true, name: true, plan: true } },
        visibilityScores: { orderBy: { computedAt: 'desc' }, take: 5 },
        recommendations: {
          where: { status: 'OPEN' },
          orderBy: { createdAt: 'desc' },
          take: 12,
        },
      },
    });
    if (!business) throw new NotFoundException('Business not found');

    // Agency white-label is product target; allow all paid plans for MVP reports
    if (organizationId && business.organizationId !== organizationId) {
      throw new ForbiddenException('Not your business');
    }

    const latest = business.visibilityScores[0];
    const fmt = (format || 'pdf').toLowerCase() === 'html' ? 'html' : 'pdf';
    const title = `Answerspot Visibility Report — ${business.name}`;
    const generatedAt = new Date().toISOString();

    const lines = [
      `Business: ${business.name}`,
      `Location: ${business.city}, ${business.state}`,
      `Category: ${business.category}`,
      `Organization: ${business.organization.name} (${business.organization.plan})`,
      `Generated: ${generatedAt}`,
      ``,
      `Visibility Score: ${latest?.score ?? 'n/a'}`,
      latest?.breakdown
        ? `Breakdown: ${JSON.stringify(latest.breakdown)}`
        : 'Breakdown: n/a',
      ``,
      `Open recommendations (${business.recommendations.length}):`,
      ...business.recommendations.map(
        (r, i) =>
          `${i + 1}. [${r.severity}] ${r.title} — ${r.message.slice(0, 80)}`,
      ),
      ``,
      `Score history:`,
      ...business.visibilityScores.map(
        (s) =>
          `  ${s.computedAt.toISOString().slice(0, 16)} → ${s.score}`,
      ),
      ``,
      `— Generated by Answerspot`,
    ];

    let body: Buffer;
    let contentType: string;
    if (fmt === 'html') {
      const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(
        title,
      )}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;color:#0f172a}
h1{font-size:1.4rem}pre{white-space:pre-wrap;background:#f8fafc;padding:1rem;border-radius:8px}</style>
</head><body><h1>${escapeHtml(title)}</h1><pre>${escapeHtml(
        lines.join('\n'),
      )}</pre></body></html>`;
      body = Buffer.from(html, 'utf8');
      contentType = 'text/html; charset=utf-8';
    } else {
      body = buildSimplePdf({ title, lines });
      contentType = 'application/pdf';
    }

    const storageKey = `reports/${businessId}/${Date.now()}.${fmt}`;
    const stored = await putReportObject(storageKey, body, contentType);

    const row = await this.prisma.report.create({
      data: {
        businessId,
        format: fmt,
        title,
        storageKey: stored.storageKey,
        url: stored.url,
        sizeBytes: body.length,
      },
    });

    return {
      id: row.id,
      businessId,
      format: fmt,
      title,
      url: stored.url,
      storageKey: stored.storageKey,
      sizeBytes: body.length,
      mode: stored.mode,
      score: latest?.score ?? null,
      createdAt: row.createdAt,
    };
  }

  async list(businessId: string, organizationId: string) {
    const biz = await this.prisma.business.findFirst({
      where: { id: businessId, organizationId, deletedAt: null },
    });
    if (!biz) throw new NotFoundException('Business not found');
    return this.prisma.report.findMany({
      where: { businessId },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
  }
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
